package com.cs102.model;

public enum SecurityEventType {
    FAILED_LOGIN,
    SUCCESSFUL_LOGIN,
    ACCOUNT_LOCKED,
    ACCOUNT_UNLOCKED,
    SUSPICIOUS_REGISTRATION,
    MULTIPLE_REGISTRATIONS,
    INVALID_INPUT,
    SQL_INJECTION_ATTEMPT,
    UNAUTHORIZED_ACCESS,
    FACE_RECOGNITION_FAILURE,
    FACE_SPOOFING_DETECTED,
    SESSION_HIJACK_ATTEMPT,
    BRUTE_FORCE_ATTACK,
    RATE_LIMIT_EXCEEDED,
    UNUSUAL_LOGIN_TIME,
    MULTIPLE_CONCURRENT_SESSIONS,
    ANOMALOUS_LOGIN_PATTERN
}
